#!/bin/bash

set -euo pipefail

RESTY_CONFIG_OPTIONS=(
      --with-compat        
      --without-http_rds_json_module                                                        
      --without-http_rds_csv_module                                                                                                                    
      --without-lua_rds_parser                                                                                                                         
      --without-mail_pop3_module                              
      --without-mail_imap_module     
      --without-mail_smtp_module                                       
      --with-http_addition_module 
      --with-http_auth_request_module 
      --with-http_dav_module 
      --with-http_gunzip_module 
      --with-http_gzip_static_module 
      --with-http_random_index_module 
      --with-http_realip_module 
      --with-http_secure_link_module 
      --with-http_slice_module 
      --with-http_ssl_module 
      --with-http_stub_status_module 
      --with-http_sub_module 
      --with-http_v2_module 
      --with-http_v3_module 
      --with-ipv6 
      --with-mail 
      --with-mail_ssl_module 
      --with-md5-asm 
      --with-sha1-asm 
      --with-stream 
      --with-stream_ssl_module 
      --with-stream_ssl_preread_module 
      --with-threads 
      --add-module=./ngx_metrics
    )

./configure -j$(nproc) "${RESTY_CONFIG_OPTIONS[@]}"
